name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            os:
              - ubuntu22.04
            otp:
              - 25.3.2-2
            elixir:
              - 1.14.5
            arch:
              - amd64
        container: ghcr.io/emqx/emqx-builder/5.1-4:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

        steps:
        - uses: actions/checkout@v1

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake

        - name: Get deps git refs for cache
          id: deps-refs
          run: |
            scripts/get-dep-refs.sh

        - name: Configure git
          run: |
            git config --global --add safe.directory "*"

        - name: load rocksdb cache
          uses: actions/cache@v2
          with:
            path: |
              _build/default/lib/rocksdb/
            key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.arch }}-${{ steps.deps-refs.outputs.DEP_ROCKSDB_REF }}

        - name: Compile
          run: |
            make

        - name: Concuerror tests
          run : |
            make concuerror_test

        - name: Smoke test
          run: |
            make smoke-test

        - name: Fault-tolerance tests
          run: |
            make ct-fault-tolerance

        - name: Consistency tests
          run: |
            make ct-consistency

        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls

        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs

        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
