name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:
        runs-on: ubuntu-latest

        container: ghcr.io/emqx/emqx-builder/5.2-9:1.15.7-26.1.2-3-ubuntu22.04

        steps:
        - uses: actions/checkout@v1

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake

        - name: Configure git
          run: |
            git config --global --add safe.directory "*"

        - name: Compile
          run: |
            make

        - name: Concuerror tests
          run : |
            make concuerror_test

        - name: Smoke test
          run: |
            make smoke-test

        - name: Fault-tolerance tests
          run: |
            make ct-fault-tolerance

        - name: Consistency tests
          run: |
            make ct-consistency

        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls

        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs

        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
