name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:
        runs-on: ubuntu-latest

        container: ghcr.io/emqx/emqx-builder/5.3-5:1.15.7-26.2.1-2-ubuntu24.04

        steps:
        - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake

        - name: Configure git
          run: |
            git config --global --add safe.directory "*"

        - name: Compile
          run: |
            make

        - name: Concuerror tests
          run : |
            make concuerror_test

        - name: Smoke test
          run: |
            make smoke-test

        - name: Fault-tolerance tests
          run: |
            make ct-fault-tolerance

        - name: Consistency tests
          run: |
            make ct-consistency

        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls

        - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
          if: always()
          with:
            name: logs
            path: _build/test/logs

        - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
          with:
            name: cover
            path: _build/test/cover
